### ISSUE TITLE
No such file or directory: 'data.json'

### ISSUE THREAD

**Issue by zeromovie** [menzi11/BullshitGenerator#138]
Traceback (most recent call last):
  File "E:/Github/BullshitGenerator-master/自动狗屁不通文章生成器.py", line 7, in <module>
    data = readJSON.读JSON文件("data.json")
  File "E:\Github\BullshitGenerator-master\readJSON.py", line 11, in 读JSON文件
    with open(fileName, mode='r', encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'data.json'

**Comment by nobodxbodon** [comment]
Mac 下刚测了没问题，Windows 下这么多人用了应该也没问题。不知是何平台？
另外，目录下确定是有`data.json`文件吗？

**Comment by zeromovie** [comment]
win10 1909  用的是 pycharm with anaconda3（python3.7）目录下确定有data.json，我再试试别的环境看看吧

**Comment by jingyuexing** [comment]
> win10 1909 用的是 pycharm with anaconda3（python3.7）目录下确定有data.json，我再试试别的环境看看吧

路径尽量避免有中文字符

**Comment by nobodxbodon** [comment]
命令行下运行一样吗？
错误信息里两个文件路径的斜杠方向不同，不知是否有关？

**Comment by zeromovie** [comment]
我试了一下命令行可以成功运行，使用的是Python官网的3. 7，路径和以前一样，没有中文，pycharm依旧报错

**Comment by jingyuexing** [comment]
> 我试了一下命令行可以成功运行，使用的是Python官网的3. 7，路径和以前一样，没有中文，pycharm依旧报错

看来是其他的原因,可能库需要调试一下，环境也需要重新测一遍
